import React from 'react';
import Link from 'next/link';
import { FileText, ArrowLeft, Mail, MapPin, Globe } from 'lucide-react';

export default function TermsOfServicePage() {
  const lastUpdated = "March 25, 2026";

  return (
    <div className="min-h-screen bg-white font-normal text-slate-900">
      {/* Header */}
      <section className="relative py-20 bg-gray-50 border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-6">
          <Link 
            href="/" 
            className="inline-flex items-center gap-2 text-brand-blue hover:text-brand-dark transition-colors mb-8 text-sm font-medium"
          >
            <ArrowLeft size={16} /> Back to Home
          </Link>
          <div className="flex items-center gap-4 mb-4 text-brand-blue">
            <div className="p-3 bg-white rounded-xl border border-blue-100 shadow-sm">
              <FileText size={32} />
            </div>
            <h1 className="text-4xl md:text-5xl font-normal text-gray-900 tracking-tight">
              Terms of Service
            </h1>
          </div>
          <p className="text-gray-500 text-lg">
            Last Updated: {lastUpdated}
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-20">
        <div className="max-w-4xl mx-auto px-6 prose prose-blue prose-lg">
          <p className="text-gray-600 leading-relaxed mb-12">
            Welcome to SL Business Index. By accessing or using our website and services, you agree to comply with and be bound by the following terms and conditions. Please read them carefully.
          </p>

          <div className="space-y-12">
            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">1</span>
                Acceptance of Terms
              </h2>
              <p className="text-gray-600 leading-relaxed">
                By using this platform, you confirm that you are at least 18 years old and legally capable of entering into binding contracts. If you do not agree to these terms, please refrain from using our services.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">2</span>
                User Accounts & Registration
              </h2>
              <ul className="list-disc pl-6 space-y-3 text-gray-600">
                <li>To list a business, you must create an account. You are responsible for maintaining the confidentiality of your login credentials.</li>
                <li>You agree to provide accurate, current, and complete information during the registration process.</li>
                <li>SL Business Index reserves the right to suspend or terminate accounts that provide false information or violate our policies.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">3</span>
                Business Listings & Content
              </h2>
              <ul className="list-none space-y-4 text-gray-600 pl-4 border-l-2 border-blue-50">
                <li><strong className="text-gray-900">Responsibility:</strong> Business owners are solely responsible for the content (images, descriptions, contact info) they upload.</li>
                <li><strong className="text-gray-900">Legal Rights:</strong> You must have the legal right to list the business and use any branding/images provided.</li>
                <li><strong className="text-gray-900">Prohibitions:</strong> We prohibit the listing of illegal services, adult content, or anything that violates the laws of Sri Lanka.</li>
                <li><strong className="text-gray-900">Right to Moderate:</strong> We reserve the right to remove or edit any listing that we deem inappropriate or inaccurate without prior notice.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">4</span>
                QR Code System Usage
              </h2>
              <p className="text-gray-600 leading-relaxed">
                The QR codes generated by our platform are intended for use with SL Business Index profiles. Tampering with, reverse-engineering, or using our QR system for fraudulent activities is strictly prohibited.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">5</span>
                Intellectual Property
              </h2>
              <p className="text-gray-600 leading-relaxed">
                The design, logo, and software of SL Business Index are our intellectual property. By listing your business, you grant us a non-exclusive license to display your business information and media on our platform for promotional purposes.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">6</span>
                Limitation of Liability
              </h2>
              <ul className="list-disc pl-6 space-y-3 text-gray-600">
                <li>SL Business Index acts as a directory service. We do not guarantee the quality, safety, or legality of the businesses listed.</li>
                <li>We are not liable for any disputes, transactions, or damages arising between users and the businesses listed on our platform.</li>
                <li>We do not guarantee that the website will be available 100% of the time due to maintenance or technical issues.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">7</span>
                Prohibited Activities
              </h2>
              <p className="text-gray-600 mb-4">Users agree not to:</p>
              <ul className="list-disc pl-6 space-y-2 text-gray-600">
                <li>Use any automated system (bots, scrapers) to extract data from the site.</li>
                <li>Post spam, repetitive content, or malicious links.</li>
                <li>Harass or impersonate other users or business owners.</li>
              </ul>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">8</span>
                Governing Law
              </h2>
              <p className="text-gray-600 leading-relaxed">
                These terms are governed by and construed in accordance with the laws of the Democratic Socialist Republic of Sri Lanka. Any disputes shall be subject to the exclusive jurisdiction of the courts in Sri Lanka.
              </p>
            </div>

            <div>
              <h2 className="text-2xl font-normal text-gray-900 mb-4 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">9</span>
                Changes to Terms
              </h2>
              <p className="text-gray-600 leading-relaxed">
                We reserve the right to modify these terms at any time. We will notify users of significant changes via email or a notice on our homepage. Continued use of the site after changes constitutes acceptance of the new terms.
              </p>
            </div>

            <div className="bg-gray-50 p-8 rounded-2xl border border-gray-200">
              <h2 className="text-2xl font-normal text-gray-900 mb-6 flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-full bg-brand-blue/10 text-brand-blue text-sm font-bold">10</span>
                Contact Information
              </h2>
              <div className="space-y-4">
                <div className="flex items-center gap-3 text-gray-600">
                  <Mail size={18} className="text-brand-blue" />
                  <span>Email: contact@slbusinessindex.com</span>
                </div>
                <div className="flex items-center gap-3 text-gray-600">
                  <MapPin size={18} className="text-brand-blue" />
                  <span>Location: Sri Lanka</span>
                </div>
                <div className="flex items-center gap-3 text-gray-600">
                  <Globe size={18} className="text-brand-blue" />
                  <Link href="https://slbusinessindex.com" className="hover:underline">slbusinessindex.com</Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
